#!/usr/bin/env python3
"""Extract unique (τ, n, m) triples from woven data and generate GAP input.

Reads woven contraction JSON files (e.g., wc_K4_Lambda14.json), extracts
all unique permutations τ with their block sizes (n, m), and writes a
GAP-format input file that can be consumed by generate_coset_reps.g.

Usage
-----
    cd python
    uv run python scripts/prepare_coset_input.py [--woven-dir PATH] [--output PATH]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Add parent for sym_contractions import
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from sym_contractions.woven import load_woven_json


def extract_unique_taus(woven_dir: Path) -> list[dict]:
    """Extract all unique (tau, n, m) triples from woven JSON files.

    Parameters
    ----------
    woven_dir : Path
        Directory containing wc_*.json files.

    Returns
    -------
    list of dict
        Each dict has keys: tau_0indexed (tuple), n (int), m (int),
        source (str, filename for provenance).
    """
    entries: list[dict] = []
    seen: set[tuple[tuple[int, ...], int, int]] = set()

    woven_files = sorted(woven_dir.glob("wc_*.json"))
    if not woven_files:
        print(f"Warning: no wc_*.json files found in {woven_dir}")
        return entries

    for wf in woven_files:
        print(f"Reading {wf.name}...")
        woven = load_woven_json(wf)

        for (nL, nR), group in woven.groups.items():
            for entry in group.entries:
                key = (entry.tau, nL, nR)
                if key not in seen:
                    seen.add(key)
                    entries.append(
                        {
                            "tau_0indexed": entry.tau,
                            "n": nL,
                            "m": nR,
                            "source": wf.name,
                        }
                    )

    print(f"Found {len(entries)} unique (tau, n, m) triples.")
    return entries


def write_gap_input(entries: list[dict], output_path: Path) -> None:
    """Write a GAP-format input file defining coset_entries.

    The output file contains a GAP variable assignment:
        coset_entries := [ rec(tau_1indexed := [...], n := ..., m := ...), ... ];

    Parameters
    ----------
    entries : list of dict
        Each dict has tau_0indexed (tuple of int), n (int), m (int).
    output_path : Path
        Where to write the .g file.
    """
    lines: list[str] = []
    lines.append("# Auto-generated by prepare_coset_input.py")
    lines.append("# Do not edit manually.")
    lines.append(f"# {len(entries)} unique (tau, n, m) entries.")
    lines.append("")
    lines.append("coset_entries := [")

    for i, entry in enumerate(entries):
        tau_0 = entry["tau_0indexed"]
        n = entry["n"]
        m = entry["m"]
        # Convert to 1-indexed for GAP
        tau_1 = [x + 1 for x in tau_0]
        comma = "," if i < len(entries) - 1 else ""
        lines.append(f"    rec(tau_1indexed := {tau_1}, n := {n}, m := {m}){comma}")

    lines.append("];")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines))
    print(f"Wrote {output_path} ({len(entries)} entries)")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Extract (tau, n, m) triples from woven data for GAP."
    )
    parser.add_argument(
        "--woven-dir",
        type=Path,
        default=Path(__file__).resolve().parent.parent.parent
        / "data"
        / "processed"
        / "woven_contractions",
        help="Directory containing wc_*.json files.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent.parent
        / "data"
        / "gap_scripts"
        / "_coset_input.g",
        help="Output GAP file path.",
    )
    args = parser.parse_args()

    entries = extract_unique_taus(args.woven_dir)
    if entries:
        write_gap_input(entries, args.output)
    else:
        print("No entries found. Not writing output.")


if __name__ == "__main__":
    main()
