"""Load and manage symmetric group character tables from GAP-generated JSON files.

This module provides utilities to load precomputed character tables generated by
GAP (stored in ../data/processed/character_tables/) and convert them to Numpy
arrays.

GAP produces character tables with partitions in lexicographic order (smallest
first, e.g., (1,1,1), (2,1), (3)), while the Python code uses reverse
lexicographic order (largest first, e.g., (3), (2,1), (1,1,1)). The loader
automatically reverses the ordering of cycle types, class sizes, and the
character table (both rows and columns) to match the Python convention.

Note
----
Character tables are generated using GAP scripts located in ../data/gap_scripts/.
Run ../data/generate_data.sh to generate the required data files.
"""

import json
from pathlib import Path
from typing import Dict, List, Tuple, TypedDict

import numpy as np


class CharacterTableData(TypedDict):
    n: int
    cycle_types: List[List[int]]
    class_sizes: np.ndarray
    characters: np.ndarray


def load_character_table(
    filepath: str | Path,
    *,
    safe_int: bool = False,
) -> CharacterTableData:
    """Load a character table from a GAP-generated JSON file.

    The data is reordered from GAP's lexicographic partition ordering to
    the reverse lexicographic ordering used by the Python MC code.

    Parameters
    ----------
    filepath : str | Path
        Path to the JSON file containing character table data.
    safe_int : bool, optional
        If ``True``, store *class_sizes* as ``dtype=object``
        (arbitrary-precision Python ints) instead of ``int64``.
        This avoids integer overflow for large *n* (n > 20).
        Default is ``False`` for backward compatibility.

    Returns
    -------
                CharacterTableData
        Dictionary containing:
        - 'n': int, degree of symmetric group
        - 'cycle_types': List of cycle types (partitions) as lists,
          in reverse lexicographic order (largest partition first)
                - 'class_sizes': NumPy array of conjugacy class sizes (int64,
                  or object when *safe_int* is True)
                - 'characters': NumPy array of character values (int64)

    Examples
    --------
    >>> from pathlib import Path
    >>> data_dir = Path(__file__).parents[2] / 'data' / 'processed' / 'character_tables'
    >>> table = load_character_table(data_dir / 'ssct_5.json')
    >>> table['n']
    5
    >>> table['cycle_types'][0]   # Largest partition first
    [5]
    >>> table['class_sizes'].shape
    (7,)
    >>> table['characters'].shape
    (7, 7)
    """
    with open(filepath, "r") as f:
        data = json.load(f)

    # GAP orders partitions lexicographically (smallest first).
    # Reverse to match Python's reverse lexicographic order (largest first).
    cycle_types: list[list[int]] = data["CharacterParameters"][::-1]
    cs_dtype = object if safe_int else np.int64
    class_sizes = np.array(data["SizesConjugacyClasses"][::-1], dtype=cs_dtype)
    # Reverse both rows (representations) and columns (conjugacy classes).
    characters = np.array(data["CharacterTable"], dtype=np.int64)[::-1, ::-1]

    return {
        "n": int(data["n"]),
        "cycle_types": cycle_types,
        "class_sizes": class_sizes,
        "characters": characters,
    }


def load_character_tables_range(
    directory: str | Path,
    n_min: int,
    n_max: int,
    filename_pattern: str = "ssct_{n}.json",
) -> Dict[int, CharacterTableData]:
    """Load character tables for a range of symmetric groups.

    Parameters
    ----------
    directory : str | Path
        Directory containing the JSON files.
    n_min : int
        Minimum n value.
    n_max : int
        Maximum n value (inclusive).
    filename_pattern : str, optional
        Filename pattern with {n} placeholder, by default "ssct_{n}.json".

    Returns
    -------
    Dict[int, CharacterTableData]
        Dictionary keyed by n, each containing character table data.

    Examfrom pathlib import Path
    >>> data_dir = Path(__file__).parents[2] / 'data' / 'processed' / 'character_tables'
    >>> tables = load_character_tables_range(data_dir
    --------
    >>> tables = load_character_tables_range('data/', 1, 10)
    >>> tables[5]['characters'].shape
    (7, 7)
    """
    directory = Path(directory)
    tables = {}

    for n in range(n_min, n_max + 1):
        filepath = directory / filename_pattern.format(n=n)
        if filepath.exists():
            tables[n] = load_character_table(filepath)
        else:
            print(f"Warning: File not found for n={n}: {filepath}")

    return tables


def compute_class_fraction(cycle_type: List[int] | Tuple[int, ...]) -> float:
    r"""Compute the class fraction |C_α| / n! for a partition α.

    Uses the explicit formula

    .. math::

        \frac{|C_\alpha|}{n!} = \frac{1}{\prod_i i^{a_i}\, a_i!}

    where *a_i* counts how many parts of α equal *i*.  All arithmetic
    stays in ``float64`` – no intermediate exceeds *n* – so this is
    safe for arbitrarily large *n* (unlike ``class_size / n!`` which
    overflows ``int64`` for n > 20).

    Parameters
    ----------
    cycle_type : list or tuple of int
        Partition in descending order, e.g. ``[3, 2, 2, 1]``.

    Returns
    -------
    float
        The class fraction, a number in (0, 1].

    Examples
    --------
    >>> compute_class_fraction([3, 1])        # |C_{(3,1)}| / 4! = 8/24
    0.3333333333333333
    >>> compute_class_fraction([1, 1, 1])     # identity class: 1/6
    0.16666666666666666
    >>> compute_class_fraction([])            # S_0: single element
    1.0
    """
    if not cycle_type:
        return 1.0

    # Count multiplicities: a_i = #{parts equal to i}
    from collections import Counter

    counts = Counter(cycle_type)
    result = 1.0
    for i, a_i in counts.items():
        # Divide by i^{a_i} * a_i!
        result /= float(i) ** a_i
        for k in range(1, a_i + 1):
            result /= float(k)
    return result


def get_class_weights(
    cycle_types_or_sizes: List[List[int]] | np.ndarray,
    n: int,
) -> np.ndarray:
    """Compute normalized weights |C_α| / n! for every conjugacy class.

    Parameters
    ----------
    cycle_types_or_sizes : list of list of int, or np.ndarray
        Either the ``cycle_types`` list from a ``CharacterTableData``
        (overflow-safe path using :func:`compute_class_fraction`), or
        a legacy ``class_sizes`` array (falls back to division by n!).
    n : int
        Degree of symmetric group S_n.

    Returns
    -------
    np.ndarray
        Normalized weights (float64), shape ``(p,)``.

    Notes
    -----
    Prefer passing ``cycle_types`` to avoid integer overflow for n > 20.
    """
    # Detect whether the caller passed cycle_types (list of lists) or
    # the legacy class_sizes ndarray.
    if isinstance(cycle_types_or_sizes, np.ndarray):
        # Legacy path – works only when class_sizes fits in int64
        import math

        return cycle_types_or_sizes / math.factorial(n)

    # Overflow-safe path
    return np.array(
        [compute_class_fraction(ct) for ct in cycle_types_or_sizes],
        dtype=np.float64,
    )


def partition_to_cycle_type_key(partition: List[int]) -> Tuple[int, ...]:
    """Convert partition to hashable cycle type key.

    Parameters
    ----------
    partition : List[int]
        Partition as descending list, e.g., [3, 2, 2].

    Returns
    -------
    Tuple[int, ...]
        Hashable tuple representation.

    Examples
    --------
    >>> partition_to_cycle_type_key([3, 2, 2])
    (3, 2, 2)
    """
    return tuple(partition)


def find_cycle_type_index(
    cycle_types: List[List[int]], target_cycle_type: List[int]
) -> int | None:
    """Find the index of a cycle type in the character table ordering.

    Parameters
    ----------
    cycle_types : List[List[int]]
        List of cycle types from character table.
    target_cycle_type : List[int]
        Cycle type to find.

    Returns
    -------
    int | None
        Index of the cycle type, or None if not found.

    Examples
    --------
    >>> cycle_types = [[5], [4, 1], [3, 2], [3, 1, 1], [2, 2, 1], [2, 1, 1, 1], [1, 1, 1, 1, 1]]
    >>> find_cycle_type_index(cycle_types, [3, 2])
    2
    """
    target_tuple = tuple(target_cycle_type)
    for i, ct in enumerate(cycle_types):
        if tuple(ct) == target_tuple:
            return i
    return None
